### ISSUE TITLE
fork自用视频讲解

### ISSUE THREAD

**Issue by Alpha-Girl** [WuTianming/ustc-new-grade-actions#2]
吴同学，你好。我觉得你写的脚本很好用，做了一个b站讲解视频[链接](https://www.bilibili.com/video/BV1Zf4y1G7C6)。如果可以的话，希望能被加到readme中😉

**Comment by WuTianming** [comment]
哇，讲解视频吗，用心了！

我刚才看了一下，是否QQ邮箱应该是smtp而不是stmp？记不太清了，有一点点印象好像是smtp

**Comment by Alpha-Girl** [comment]
我在弹幕 更正一下🤣

**Comment by WuTianming** [comment]
已添加到readme
